apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: product-infrastructure
  title: Product infrastructure template
  description: Product infrastructure template, allows creating app insights, and Azure Key Vault.
  tags:
    - recommended
    - terraform
    - infrastructure
    - application-insights
    - azure
    - key-vault
    - secret
spec:
  owner: dts_platform_operations
  type: service
  templater: cookiecutter
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Product
          type: string
          description: Product this component belongs to, normally the team name, e.g. cmc
        description:
          title: Description
          type: string
          description: Description of the application, a sensible default will be used if not specified.
        enable_app_insights:
          title: Add application insights
          type: boolean
          default: true
          description: We use application insights for logging, do you want to deploy it?
        enable_key_vault:
          title: Add Azure Key Vault
          type: boolean
          description: Azure Key Vault is used for storing secrets, do you want to deploy it?
        product_group_name:
          title: Product Group Name
          type: string
          description: (Optional, required if deploying a key vault), Your teams Azure AD group name.

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          enable_app_insights: '{{ parameters.enable_app_insights }}'
          enable_key_vault: '{{ parameters.enable_key_vault }}'
          product_group_name: '{{ parameters.product_group_name }}'
          owner: '{{ parameters.owner }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.component_id }}'
        repoUrl: '{{ parameters.repoUrl }}'
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'
  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
