apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{ cookiecutter.product }}-product-infrastructure"
  description: {{ cookiecutter.description }}
spec:
  type: service
  lifecycle: experimental
  owner: {{ cookiecutter.owner }}
